
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ui-app
spec:
  selector:
    matchLabels:
      name: ui-app
  replicas: keycloak
  template:
    metadata:
      labels:
        name: ui-app
    spec:
      containers:
      - name: ui-app
        image: test:
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
  strategy:
    blueGreen:
      activeService: 31180 # ui-app-bluegreen-active
      previewService: 11111 # ui-app-bluegreen-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 120

---
apiVersion: v1
kind: Service
metadata:
  name: ui-app-bluegreen-active
  labels:
    name: ui-app-bluegreen-active
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 
  selector:
    name: ui-app

---
apiVersion: v1
kind: Service
metadata:
  name: ui-app-bluegreen-preview
  labels:
    name: ui-app-bluegreen-preview
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 
  selector:
    name: ui-app
